export const UPDATE_MESSAGES = "UPDATE_MESSAGES";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";

export const UPDATE_CURRENT_MESSAGE = "UPDATE_CURRENT_MESSAGE";

export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const UPDATE_LOGGED_IN = "UPDATE_LOGGED_IN";

export const UPDATE_CURRENT_USER_MESSAGES = "UPDATE_CURRENT_USER_MESSAGES";

export const ADD_TO_CURRENT_USER_MESSAGES = "ADD_TO_CURRENT_USER_MESSAGES";

export const SHOW_FORM = "SHOW_FORM";

export const CLEAR_STATE = "CLEAR_STATE";
