export const UPDATE_MESSAGES = "UPDATE_MESSAGES";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";

export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const UPDATE_LOGGED_IN = "UPDATE_LOGGED_IN";

export const UPDATE_CURRENT_MESSAGE = "UPDATE_CURRENT_MESSAGE";
